feat: Cleanup
- envrc

- cq-sweep.py
Remove the try except ImportError we'll just let it report the Error:
```
$ ./cq-sweep.py
Traceback (most recent call last):
  File "/home/wink/data/prgs/3dprinting/cq-sweep/./cq-sweep.py", line 3, in <module>
    import cadquery as cq
ModuleNotFoundError: No module named 'cadquery'
```

Make args.show a boolean and that defaults to True and turn it off using
--no-show or -ns. Since that args.show is a boolean change the
if statement to just be `if args.show:`.